<?php
return [
    'tshirt_small' => [
        'name' => 'Camiseta Pequeña',
        'panel_width_cm' => 30,
        'panel_height_cm' => 40,
        'gusset_cm' => 8,
        'fold_allowance_cm' => 3,
        'seam_allowance_cm' => 1.2,
        'fabric_weight_gsm' => 60,
        'default_fabric_cost_per_meter' => 1.85,
        'default_thread_per_bag_m' => 3.5,
        'default_thread_spool_length_m' => 2500,
        'default_thread_spool_cost' => 3.15,
        'default_labor_cost_per_bag' => 0.12,
    ],
    'tshirt_large' => [
        'name' => 'Camiseta Grande',
        'panel_width_cm' => 40,
        'panel_height_cm' => 50,
        'gusset_cm' => 10,
        'fold_allowance_cm' => 4,
        'seam_allowance_cm' => 1.5,
        'fabric_weight_gsm' => 70,
        'default_fabric_cost_per_meter' => 2.1,
        'default_thread_per_bag_m' => 4.2,
        'default_thread_spool_length_m' => 2500,
        'default_thread_spool_cost' => 3.45,
        'default_labor_cost_per_bag' => 0.16,
    ],
    'flat_wine' => [
        'name' => 'Botella (Vino)',
        'panel_width_cm' => 20,
        'panel_height_cm' => 35,
        'gusset_cm' => 10,
        'fold_allowance_cm' => 5,
        'seam_allowance_cm' => 1,
        'fabric_weight_gsm' => 80,
        'default_fabric_cost_per_meter' => 2.4,
        'default_thread_per_bag_m' => 5.3,
        'default_thread_spool_length_m' => 2000,
        'default_thread_spool_cost' => 4.1,
        'default_labor_cost_per_bag' => 0.22,
    ],
    'box_premium' => [
        'name' => 'Tipo Caja Premium',
        'panel_width_cm' => 35,
        'panel_height_cm' => 45,
        'gusset_cm' => 14,
        'fold_allowance_cm' => 6,
        'seam_allowance_cm' => 1.5,
        'fabric_weight_gsm' => 90,
        'default_fabric_cost_per_meter' => 2.85,
        'default_thread_per_bag_m' => 6.1,
        'default_thread_spool_length_m' => 2000,
        'default_thread_spool_cost' => 4.6,
        'default_labor_cost_per_bag' => 0.28,
    ],
];
