<?php
return [
    'bolsa-camiseta-60' => [
        'name' => 'Bolsa Camiseta 60 g/m²',
        'category' => 'Bolsas Camiseta',
        'model' => 'tshirt_small',
        'short_description' => 'Bolsa tipo camiseta ligera para supermercados y conveniencia.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-camiseta-60/',
        'defaults' => [
            'quantity' => 2000,
            'fabric_roll_width_cm' => 160,
            'fabric_roll_length_m' => 600,
            'fabric_cost_per_meter' => 1.8,
            'labor_cost_per_bag' => 0.11,
            'thread_per_bag_m' => 3.2,
            'thread_spool_length_m' => 2500,
            'thread_spool_cost' => 3.2,
            'additional_costs' => 90,
        ],
        'notes' => 'Disponible en colores blanco, azul y rojo.',
    ],
    'bolsa-camiseta-80' => [
        'name' => 'Bolsa Camiseta 80 g/m²',
        'category' => 'Bolsas Camiseta',
        'model' => 'tshirt_large',
        'short_description' => 'Modelo reforzado con asas troqueladas para cargas pesadas.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-camiseta-80/',
        'defaults' => [
            'quantity' => 1500,
            'fabric_roll_width_cm' => 160,
            'fabric_roll_length_m' => 500,
            'fabric_cost_per_meter' => 2.05,
            'labor_cost_per_bag' => 0.15,
            'thread_per_bag_m' => 3.9,
            'thread_spool_length_m' => 2400,
            'thread_spool_cost' => 3.4,
            'additional_costs' => 110,
        ],
        'notes' => 'Troquelado doble para refuerzo en asa.',
    ],
    'bolsa-supermercado-gusset' => [
        'name' => 'Bolsa Supermercado con fuelle',
        'category' => 'Bolsas con Fuelle',
        'model' => 'grocery_large',
        'short_description' => 'Bolsa reusable amplia para compras semanales.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-supermercado/',
        'defaults' => [
            'quantity' => 1200,
            'fabric_roll_width_cm' => 160,
            'fabric_roll_length_m' => 450,
            'fabric_cost_per_meter' => 3.15,
            'labor_cost_per_bag' => 0.34,
            'thread_per_bag_m' => 6.5,
            'thread_spool_length_m' => 2000,
            'thread_spool_cost' => 4.9,
            'additional_costs' => 180,
        ],
        'notes' => 'Incluye base cuadrada y asa de cinta.',
    ],
    'bolsa-regalo-premium' => [
        'name' => 'Bolsa Tipo Caja Premium',
        'category' => 'Bolsas con Fuelle',
        'model' => 'box_premium',
        'short_description' => 'Bolsa rígida con acabado premium para boutiques.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-premium/',
        'defaults' => [
            'quantity' => 800,
            'fabric_roll_width_cm' => 150,
            'fabric_roll_length_m' => 400,
            'fabric_cost_per_meter' => 2.95,
            'labor_cost_per_bag' => 0.29,
            'thread_per_bag_m' => 6.1,
            'thread_spool_length_m' => 2000,
            'thread_spool_cost' => 4.7,
            'additional_costs' => 210,
        ],
        'notes' => 'Personalización con serigrafía o transfer.',
    ],
    'bolsa-vino-individual' => [
        'name' => 'Bolsa Individual para Botella',
        'category' => 'Bolsas para Botella',
        'model' => 'flat_wine',
        'short_description' => 'Presentación elegante para botellas de vino o licor.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-botella/',
        'defaults' => [
            'quantity' => 1000,
            'fabric_roll_width_cm' => 140,
            'fabric_roll_length_m' => 420,
            'fabric_cost_per_meter' => 2.55,
            'labor_cost_per_bag' => 0.23,
            'thread_per_bag_m' => 5.1,
            'thread_spool_length_m' => 2000,
            'thread_spool_cost' => 4.2,
            'additional_costs' => 160,
        ],
        'notes' => 'Se entrega con separador interno opcional.',
    ],
    'bolsa-vino-doble' => [
        'name' => 'Bolsa Doble para Botellas',
        'category' => 'Bolsas para Botella',
        'model' => 'wine_double',
        'short_description' => 'Compartimentos dobles con refuerzo en base.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-doble-botella/',
        'defaults' => [
            'quantity' => 900,
            'fabric_roll_width_cm' => 150,
            'fabric_roll_length_m' => 420,
            'fabric_cost_per_meter' => 2.75,
            'labor_cost_per_bag' => 0.26,
            'thread_per_bag_m' => 5.8,
            'thread_spool_length_m' => 2000,
            'thread_spool_cost' => 4.4,
            'additional_costs' => 175,
        ],
        'notes' => 'Incluye divisor fijo y asa reforzada.',
    ],
    'morral-nonwoven' => [
        'name' => 'Morral Non Woven',
        'category' => 'Morrales y Mochilas',
        'model' => 'drawstring_pack',
        'short_description' => 'Morral ligero con cordón para eventos masivos.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/morral-nonwoven/',
        'defaults' => [
            'quantity' => 2500,
            'fabric_roll_width_cm' => 150,
            'fabric_roll_length_m' => 500,
            'fabric_cost_per_meter' => 2.2,
            'labor_cost_per_bag' => 0.21,
            'thread_per_bag_m' => 5.4,
            'thread_spool_length_m' => 2400,
            'thread_spool_cost' => 3.5,
            'additional_costs' => 130,
        ],
        'notes' => 'Cordones en color negro o blanco.',
    ],
    'mochila-reforzada' => [
        'name' => 'Mochila Reforzada Non Woven',
        'category' => 'Morrales y Mochilas',
        'model' => 'drawstring_pack',
        'short_description' => 'Mochila con panel frontal sublimable y ojillos metálicos.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/mochila-reforzada/',
        'defaults' => [
            'quantity' => 1800,
            'fabric_roll_width_cm' => 150,
            'fabric_roll_length_m' => 420,
            'fabric_cost_per_meter' => 2.5,
            'labor_cost_per_bag' => 0.25,
            'thread_per_bag_m' => 5.9,
            'thread_spool_length_m' => 2200,
            'thread_spool_cost' => 3.8,
            'additional_costs' => 155,
        ],
        'notes' => 'Disponible con cordón bicolor.',
    ],
    'portadocumentos-cierre' => [
        'name' => 'Portadocumentos con cierre',
        'category' => 'Portadocumentos',
        'model' => 'zippered_case',
        'short_description' => 'Estuche horizontal con cierre y asa lateral.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/portadocumentos-cierre/',
        'defaults' => [
            'quantity' => 2200,
            'fabric_roll_width_cm' => 150,
            'fabric_roll_length_m' => 500,
            'fabric_cost_per_meter' => 2.05,
            'labor_cost_per_bag' => 0.2,
            'thread_per_bag_m' => 4.2,
            'thread_spool_length_m' => 2500,
            'thread_spool_cost' => 3.4,
            'additional_costs' => 140,
        ],
        'notes' => 'Ideal para congresos y convenciones.',
    ],
    'lonchera-termica' => [
        'name' => 'Lonchera Térmica Non Woven',
        'category' => 'Térmicas y Lunch Bags',
        'model' => 'cooler_lunch',
        'short_description' => 'Bolsa térmica con cierre y bolsa frontal.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/lonchera-termica/',
        'defaults' => [
            'quantity' => 1400,
            'fabric_roll_width_cm' => 140,
            'fabric_roll_length_m' => 380,
            'fabric_cost_per_meter' => 3.7,
            'labor_cost_per_bag' => 0.4,
            'thread_per_bag_m' => 7.2,
            'thread_spool_length_m' => 1800,
            'thread_spool_cost' => 5.6,
            'additional_costs' => 220,
        ],
        'notes' => 'Incluye espuma y recubrimiento aluminizado.',
    ],
    'bolsa-plana-chica' => [
        'name' => 'Bolsa Plana Chica',
        'category' => 'Bolsas Planas',
        'model' => 'zippered_case',
        'short_description' => 'Formato sencillo sin fuelle para empaques ligeros.',
        'image' => null,
        'url' => 'https://proactivatextil.com.mx/producto/bolsa-plana-chica/',
        'defaults' => [
            'quantity' => 3000,
            'fabric_roll_width_cm' => 140,
            'fabric_roll_length_m' => 550,
            'fabric_cost_per_meter' => 1.95,
            'labor_cost_per_bag' => 0.14,
            'thread_per_bag_m' => 3.8,
            'thread_spool_length_m' => 2600,
            'thread_spool_cost' => 3.3,
            'additional_costs' => 100,
        ],
        'notes' => 'Se entrega doblada con sellado ultrasonido.',
    ],
];
